---
kind: pipeline
type: docker
name: linux

platform:
  os: linux
  arch: amd64

steps:
- name: minify_pack
  image: patwie/dms-release:latest
  commands:
  - rm -rf static.min
  - mkdir static.min
  - mkdir static.min/fonts
  - mkdir static.min/css
  - mkdir static.min/js
  - minify -o static.min/css/min.css static/css/main.css static/css/all.min.css
  - minify -o static.min/index.html static/index.html
  - minify -o static.min/js/min.js static/js/jquery-3.4.1.min.js static/js/fuzzysort.js static/js/pdf.js static/js/pdf.worker.js static/js/main.js
  - "cp static/fonts/* static.min/fonts/"
  - /go/bin/packr2

- name: build-linux-amd64
  image: golang:1.13
  commands:
  - dir
  - go build
  - mv digitalmusicstand digitalmusicstand-linux-amd64
  environment:
    GOARCH: amd64
    GOOS: linux

- name: build-linux-arm64
  image: golang:1.13
  commands:
  - dir
  - go build
  - mv digitalmusicstand digitalmusicstand-linux-arm64
  environment:
    GOARCH: arm64
    GOOS: linux

- name: build-linux-arm
  image: golang:1.13
  commands:
  - dir
  - go build
  - mv digitalmusicstand digitalmusicstand-linux-arm
  environment:
    GOARCH: arm
    GOOS: linux

- name: build-windows-amd64
  image: golang:1.13
  commands:
  - dir
  - go build
  - mv digitalmusicstand.exe digitalmusicstand-windows-amd64.exe
  environment:
    GOARCH: amd64
    GOOS: windows

- name: create_release
  image: patwie/tar:latest
  commands:
  - zip -rv digitalmusicstand-windows-amd64.zip README.md digitalmusicstand-windows-amd64.exe
  - tar -czvf digitalmusicstand-linux-amd64.tar.gz README.md  digitalmusicstand-linux-amd64
  - tar -czvf digitalmusicstand-linux-arm.tar.gz README.md  digitalmusicstand-linux-arm
  - tar -czvf digitalmusicstand-linux-arm64.tar.gz README.md  digitalmusicstand-linux-arm64

- name: upload_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - md5
    - sha256
    files:
    - digitalmusicstand-windows-amd64.zip
    - digitalmusicstand-linux-amd64.tar.gz
    - digitalmusicstand-linux-arm64.tar.gz
    - digitalmusicstand-linux-arm.tar.gz
  when:
    event:
    - tag

---
kind: signature
hmac: af20957923d1dc19caa79fe21ab8504c8834c73799da7fc0216028f6c6506206

...
